name: 'Run semgrep'
description: 'Run semgrep with reviewdog on pull requests.'
author: 'GTsigourakos'
inputs:
  semgrep_flags:
    description: 'Semgrep custom additional flags.'
    default: '--disable-version-check --config=auto'
    required: false
  semgrep_ignore:
    description: 'Specify a custom semgrep ignore fingerprint file from a URL.'
    default: ''
    required: false
  changed_files:
    description: The changed files that need to be checked.
    default: ''
    required: false
  semgrep_comment:
    description: 'Comment semgrep output'
    required: false
    default: 'false'
  artifact:
    description: 'Artifact file'
    default: 'report.semgrep.json'
    required: false

runs:
  using: 'composite'
  steps:
  - run: $GITHUB_ACTION_PATH/entrypoint.sh
    shell: bash
    env:
      INPUT_SEMGREP_FLAGS: ${{ inputs.semgrep_flags }}
      INPUT_SEMGREP_IGNORE: ${{ inputs.semgrep_ignore }}
      INPUT_SEMGREP_COMMENT: ${{ inputs.semgrep_comment }}
      INPUT_CHANGED_FILES: ${{ inputs.changed_files }}
      INPUT_ARTIFACT: ${{ inputs.artifact }}

branding:
  icon: 'check-circle'
  color: 'red'
